using Wyag.Core.Refs;

namespace Wyag.Core.Objects;

public sealed class TagService(IObjectStore os, IObjectResolver or, IRefStore rs)
    : ITagService
{
    public void Create(GitRepository repo, string name, string reference, bool createTagObject)
    {
        var sha = or.Find(repo, reference);

        if (createTagObject)
        {
            var tag = new GitTag();
            tag.Kvlm.Add("object", sha);
            tag.Kvlm.Add("type", "commit");
            tag.Kvlm.Add("tag", name);
            tag.Kvlm.Add("tagger", "Wyag <example@domain.com>");
            tag.Kvlm.Message = "A tag generated by wyag.";

            var tagSha = os.Write(tag, repo);
            rs.Create(repo, $"tags/{name}", tagSha);
        }
        else
        {
            rs.Create(repo, $"tags/{name}", sha);
        }

    }
}
